-- ============================================================
-- NAVITA TUITIONS - COMPLETE SUPABASE DATABASE SCHEMA
-- PostgreSQL / Supabase
-- ============================================================

-- ============================================================
-- 1. PROFILES
-- Extends Supabase's built-in auth.users table
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    email text,
    role text not null default 'student'
        check (role in ('student', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 2. ENQUIRIES (Lead Management)
-- Stores consultation requests and admission enquiries
-- ============================================================

create table if not exists public.enquiries (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null,
    email text,
    student_grade text not null,
    board text not null,
    subjects text not null,
    mode text not null default 'Offline Tuition',
    message text,
    status text not null default 'new'
        check (status in ('new', 'contacted', 'enrolled', 'closed')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 3. WORKSHEET CATEGORIES
-- ============================================================

create table if not exists public.worksheet_categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    created_at timestamptz not null default now()
);


-- ============================================================
-- 4. WORKSHEETS
-- ============================================================

create table if not exists public.worksheets (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    category_id bigint
        references public.worksheet_categories(id)
        on delete set null,
    file_path text not null,
    thumbnail_path text,
    is_free boolean not null default false,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 5. PAYMENTS
-- ============================================================

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references auth.users(id)
        on delete cascade,
    amount numeric(10,2) not null
        check (amount >= 0),
    currency text not null default 'INR',
    payment_status text not null default 'pending'
        check (
            payment_status in (
                'pending',
                'successful',
                'failed',
                'refunded'
            )
        ),
    payment_provider text,
    payment_id text unique,
    order_id text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- 6. USER ACCESS
-- ============================================================

create table if not exists public.user_access (
    id bigint generated by default as identity primary key,
    user_id uuid not null
        references auth.users(id)
        on delete cascade,
    worksheet_id bigint not null
        references public.worksheets(id)
        on delete cascade,
    access_type text not null default 'purchase'
        check (
            access_type in (
                'purchase',
                'admin',
                'manual',
                'subscription'
            )
        ),
    granted_at timestamptz not null default now(),
    expires_at timestamptz,
    unique (user_id, worksheet_id)
);


-- ============================================================
-- 7. UPDATED_AT FUNCTION & TRIGGERS
-- ============================================================

create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.update_updated_at();

drop trigger if exists enquiries_updated_at on public.enquiries;
create trigger enquiries_updated_at
before update on public.enquiries
for each row execute function public.update_updated_at();

drop trigger if exists worksheets_updated_at on public.worksheets;
create trigger worksheets_updated_at
before update on public.worksheets
for each row execute function public.update_updated_at();

drop trigger if exists payments_updated_at on public.payments;
create trigger payments_updated_at
before update on public.payments
for each row execute function public.update_updated_at();


-- ============================================================
-- 8. AUTOMATIC PROFILE CREATION ON USER SIGNUP
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, email)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        new.email
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();


-- ============================================================
-- 9. ROW LEVEL SECURITY (RLS)
-- ============================================================

alter table public.profiles enable row level security;
alter table public.enquiries enable row level security;
alter table public.worksheet_categories enable row level security;
alter table public.worksheets enable row level security;
alter table public.payments enable row level security;
alter table public.user_access enable row level security;


-- ============================================================
-- 10. HELPER FUNCTION - ADMIN CHECK
-- ============================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
        and role = 'admin'
    );
$$;


-- ============================================================
-- 11. ENQUIRIES POLICIES
-- - Anyone (anonymous / authenticated) can SUBMIT enquiries
-- - Only Admins can VIEW and MANAGE enquiries
-- ============================================================

drop policy if exists "Anyone can submit enquiry" on public.enquiries;
create policy "Anyone can submit enquiry"
on public.enquiries
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can view and manage enquiries" on public.enquiries;
create policy "Admins can view and manage enquiries"
on public.enquiries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());


-- ============================================================
-- 12. PROFILE POLICIES
-- ============================================================

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());


-- ============================================================
-- 13. CATEGORY & WORKSHEET POLICIES
-- ============================================================

drop policy if exists "Anyone can view categories" on public.worksheet_categories;
create policy "Anyone can view categories"
on public.worksheet_categories
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage categories" on public.worksheet_categories;
create policy "Admins can manage categories"
on public.worksheet_categories
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Anyone can view published worksheets" on public.worksheets;
create policy "Anyone can view published worksheets"
on public.worksheets
for select
to anon, authenticated
using (is_published = true);

drop policy if exists "Admins can manage worksheets" on public.worksheets;
create policy "Admins can manage worksheets"
on public.worksheets
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());


-- ============================================================
-- 14. PAYMENT & USER ACCESS POLICIES
-- ============================================================

drop policy if exists "Users can view own payments" on public.payments;
create policy "Users can view own payments"
on public.payments
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users can view own access" on public.user_access;
create policy "Users can view own access"
on public.user_access
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can manage user access" on public.user_access;
create policy "Admins can manage user access"
on public.user_access
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());


-- ============================================================
-- 15. INDEXES
-- ============================================================

create index if not exists idx_enquiries_created on public.enquiries(created_at desc);
create index if not exists idx_enquiries_status on public.enquiries(status);
create index if not exists idx_worksheets_category on public.worksheets(category_id);
create index if not exists idx_worksheets_published on public.worksheets(is_published);
create index if not exists idx_payments_user on public.payments(user_id);
create index if not exists idx_payments_status on public.payments(payment_status);
create index if not exists idx_user_access_user on public.user_access(user_id);
create index if not exists idx_user_access_worksheet on public.user_access(worksheet_id);
